### ISSUE TITLE
Install Keypair

### ISSUE THREAD

**Issue by cregkly** [GeoffWilliams/sshkeys#1]
I am at a loss how this is supposed to work, as the source path for getting the contents of the file resolves as a local path. Without the puppet:// prefix it will always look on the local machine rather than the puppet server.

**Comment by GeoffWilliams** [comment]
The original idea was to read files from the puppet master using the `file()` function, with one set of puppet classes to create the files on the master and another set to download it on the agent nodes. This is very clunky and wasn't well documented. Resolved in latest release
