### ISSUE TITLE
install_keypair uses wrong filenames

### ISSUE THREAD

**Issue by rogermartensson** [GeoffWilliams/sshkeys#4]
When using sshkeys::install_keypair it uses the wrong filenames for the private and public key. It should be in the format "id_rsa" and "id_rsa.pub" where rsa is the algorithm used.

Looks like it is only uses the supplied title.

**Comment by GeoffWilliams** [comment]
Thanks for this, added a new parameter `default_files` - set true to write id_rsa/id_rsa.pub

In the past, this module was used to install a bunch of keys but this makes sense if your only installing one
